/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalworktry;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Baiba
 */
public class Game extends javax.swing.JPanel {

    ArrayList<JButton> buttons = new ArrayList<>();
    ArrayList<ImageIcon> iconList = new ArrayList<>();

    public Game() {
        initComponents();
        label.setText(String.valueOf(moves));
        label2.setText("Pirmais logs");

        buttons.add(b1);
        buttons.add(b2);
        buttons.add(b3);
        buttons.add(b4);
        buttons.add(b5);
        buttons.add(b6);
        buttons.add(b7);
        buttons.add(b8);
        buttons.add(b9);

//        buttons.get(0).setIcon(defIcon);
//        buttons.get(1).setIcon(defIcon);
//        buttons.get(2).setIcon(defIcon);
//        buttons.get(3).setIcon(defIcon);
//        buttons.get(4).setIcon(defIcon);
//        buttons.get(5).setIcon(defIcon);
//        buttons.get(6).setIcon(defIcon);
//        buttons.get(7).setIcon(defIcon);
//        buttons.get(8).setIcon(defIcon);
        ImageIcon icon2 = new ImageIcon("src\\images\\icon2.jpg");
        ImageIcon icon3 = new ImageIcon("src\\images\\icon3.jpg");
        ImageIcon icon4 = new ImageIcon("src\\images\\icon4.jpg");
        iconList.add(icon2);
        iconList.add(icon2);
        iconList.add(icon2);
        iconList.add(icon3);
        iconList.add(icon3);
        iconList.add(icon3);
        iconList.add(icon4);
        iconList.add(icon4);
        iconList.add(icon4);
        Collections.shuffle(iconList);

//        for (int i = 0; i < buttons.size(); i++) {
//            buttons.get(i).setIcon(iconList.get(i));
//        }
    }

    boolean visible = true;
    boolean nextMove = false;
    boolean isMatch = false;
    boolean oneSelected = false;
    boolean twoSelected = false;
    int moves = 2;
    JButton selected1 = null;
    JButton selected2 = null;

    //ImageIcon defIcon = new ImageIcon("src\\images\\icon.jpg");
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();

        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        label.setText("jLabel1");

        label2.setText("jLabel1");

        label3.setText("jLabel1");

        label4.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(label)
                        .addGap(69, 69, 69)
                        .addComponent(label2)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(label3)
                        .addGap(67, 67, 67)
                        .addComponent(label4))
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(b1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label)
                    .addComponent(label2)
                    .addComponent(label3)
                    .addComponent(label4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

//    public void actionPerf(ActionEvent evt) {
//        JButton button = (JButton) evt.getSource();
//        for (int i = buttons.size(); i < buttons.size(); i++) {
//            if (button != buttons.get(i)) {
//                button.setIcon(iconList.get(i));
//                break;
//
//            }
//
//        }
//        label3.setText("oooooo");
//    }
    private void clearIcons() {
//        if (!noMatch) {
//            label2.setText("nesakrīt222");
//            selected1.setIcon(null);
//            selected2.setIcon(null);
//        }
//        if (!noMatch && selected1 != null) {//sakrīt
//            selected1.setIcon(null);
//            selected2.setIcon(null);
//            selected1 = null;
//            selected2 = null;
//        }
//        if (!isMatch && selected1 != null && selected2 != null) {//nesakrīt
//            label3.setText(String.valueOf(isMatch));
//            selected1.setIcon(null);
//            selected2.setIcon(null);
//            selected1 = null;
//            selected2 = null;
//        }
        if (!isMatch && oneSelected && twoSelected) {//sakrīt
            label3.setText("onesel&&twosel" + String.valueOf(isMatch));
            selected1.setIcon(null);
            selected2.setIcon(null);
            selected1 = null;
            selected2 = null;
            oneSelected = false;
            twoSelected = false;
        }
        if (isMatch && oneSelected && twoSelected) {
            selected1 = null;
            selected2 = null;
            oneSelected = false;
            twoSelected = false;
        }

    }

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
//        b9.addActionListener(this);

        clearIcons();
        label.setText(String.valueOf(oneSelected));

//        if (b9 != selected1 || b9 != selected2) {
        if (!oneSelected) {
            selected1 = b9;
            // label.setText("selected1");
            b9.setIcon(iconList.get(8));
            oneSelected = true;
        }
        if (oneSelected) {
            selected2 = b9;
            //label.setText("selected2");
            b9.setIcon(iconList.get(8));
            twoSelected = true;
        }

        moves--;
        countMoves();
        matchIcons();

//        }
//        for (int i = buttons.size(); i < buttons.size(); i++) {
//            if (b9 == buttons.get(i))
//            {
//                b9.setIcon(iconList.get(i));
//                break;        
//            } 
//        }

    }//GEN-LAST:event_b9ActionPerformed


    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed

        clearIcons();
        label.setText(String.valueOf(oneSelected));

//        if (b6 != selected1 || b6 != selected2) {
        if (!oneSelected) {
            selected1 = b6;
            //label.setText("selected1");
            oneSelected = true;
            b6.setIcon(iconList.get(5));
        }
        if (oneSelected) {
            selected2 = b6;
            // label.setText("selected2");
            twoSelected = true;
            b6.setIcon(iconList.get(5));
        }
        
        moves--;
        countMoves();
        matchIcons();
//        }

    }//GEN-LAST:event_b6ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed

        clearIcons();

//        if (b3 != selected1 || b3 != selected2) {
        if (!oneSelected) {
            selected1 = b3;
            label.setText("selected1");
            oneSelected = true;
            b3.setIcon(iconList.get(2));
        }
        if (oneSelected) {
            selected2 = b3;
            label.setText("selected2");
            twoSelected = true;
            b3.setIcon(iconList.get(2));
        }
        
        moves--;
        countMoves();
        matchIcons();
//        }

    }//GEN-LAST:event_b3ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed

        clearIcons();

//        if (b2 != selected1 || b2 != selected2) {
        if (!oneSelected) {
            selected1 = b2;
            label.setText("selected1");
            oneSelected = true;
            b2.setIcon(iconList.get(1));
        }
        if (oneSelected) {
            selected2 = b2;
            label.setText("selected2");
            twoSelected = true;
            b2.setIcon(iconList.get(1));
        }
        
        moves--;

        matchIcons();
        countMoves();

//        }
    }//GEN-LAST:event_b2ActionPerformed
    private void matchIcons() {
//        if (selected1 == null || selected2 == null){
//            nextMove = false;
//        }
if (!twoSelected){
            label2.setText("Vēl vienu");
        }
        if (oneSelected && twoSelected) {
            if (selected1.getIcon() == selected2.getIcon()) {
                label2.setText("sakrīt!");
                //nextMove = false;
                isMatch = true;
                label4.setText(String.valueOf(isMatch));
            }
            if (selected1.getIcon() != selected2.getIcon()) {
                label2.setText("nesakrīt");
//                selected1.setIcon(defIcon);
//                selected2.setIcon(defIcon);
                //nextMove = false;

                isMatch = false;
                label4.setText(String.valueOf(isMatch));
            }

        }
        

//        label2.setText("nesakrīt");
//        selected1.setIcon(null);
//        selected2.setIcon(null);
    }

    private void selectedMatch() {

    }

    private void countMoves() {
        //label.setText(String.valueOf(moves));
//        if (nextMove) {
        //moves = 2;
//            selected1 = null;
//            selected2 = null;

//        }
//        if (moves == 0) {
//            nextMove = false;
//        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    // End of variables declaration//GEN-END:variables

//    @Override
//    public void actionPerformed(ActionEvent evt) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
//    @Override
//    public void actionPerformed(ActionEvent e) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
}
