/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package numberguess;

import java.awt.event.KeyEvent;
import java.util.Random;

/**
 *
 * @author Baiba
 */
public class Game extends javax.swing.JPanel {

    int number;
    int guess;
    int count;
    int wins = 0;
    int losses = 0;
    boolean guessed;

    public Game() {
        initComponents();
        remain.setText("Guesses remaining: -");
        results.setText("Wins: " + wins + "  |  Losses: " + losses);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultText = new javax.swing.JLabel();
        generate = new javax.swing.JButton();
        numberGuess = new javax.swing.JTextField();
        btnCheck = new javax.swing.JButton();
        remain = new javax.swing.JLabel();
        task = new javax.swing.JLabel();
        guessList = new java.awt.List();
        title = new javax.swing.JLabel();
        results = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        generate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        generate.setText("Generate new number");
        generate.setRequestFocusEnabled(false);
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });

        numberGuess.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        numberGuess.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numberGuess.setNextFocusableComponent(numberGuess);
        numberGuess.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numberGuessKeyPressed(evt);
            }
        });

        btnCheck.setText("OK");
        btnCheck.setFocusPainted(false);
        btnCheck.setNextFocusableComponent(numberGuess);
        btnCheck.setRequestFocusEnabled(false);
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        remain.setText("Guesses remaining: ");

        task.setText("Enter number from 1 to 100!");

        guessList.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        title.setFont(new java.awt.Font("Tekton Pro", 1, 48)); // NOI18N
        title.setText("Guess a number!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(results, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(resultText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(remain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(generate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(numberGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCheck))
                                    .addComponent(task))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guessList, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(title))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(generate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(task)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numberGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(14, 14, 14)
                        .addComponent(resultText, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(remain, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(results, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(guessList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
        Random rand = new Random();
        number = rand.nextInt(100) + 1;
        System.out.println(number);
        guessList.removeAll();
        numberGuess.setText("");
        resultText.setText("");
        count = 10;
        guessed = false;
        remain.setText("Guesses remaining: " + count);
        numberGuess.requestFocus();
    }//GEN-LAST:event_generateActionPerformed

    private void checkNumber() {
        String itemCount = String.valueOf(guessList.getItemCount() + 1) + ".  " + numberGuess.getText();
        if (number == 0) {
            resultText.setText("Generate random number!");
        } else if (numberGuess.getText().equals("") && count > 0) {
            resultText.setText("Enter number!");
            numberGuess.setText("");
        } else if (count > 0 && !guessed) {
            try {
                guess = Integer.valueOf(numberGuess.getText());

                if (guess > 100 || guess < 1) {
                    resultText.setText("Enter number from 1 to 100!");
                } else if (guess > number) {
                    resultText.setText("Number too big");
                    count--;
                    guessList.add(itemCount + " - - -");
                } else if (guess < number) {
                    resultText.setText("Number too low");
                    count--;
                    guessList.add(itemCount + " +++");
                } else if (guess == number) {
                    resultText.setText("Guessed!");
                    guessList.add(itemCount + " ===");
                    guessed = true;
                    wins++;
                }
                if (count == 0) {
                    resultText.setText("No moves left! Correct answer: " + number);
                    losses++;
                }
            } catch (Exception e) {
                resultText.setText("Enter number from 1 to 100!");
                numberGuess.setText("");
            }
            remain.setText("Guesses remaining: " + count);
            numberGuess.setText("");
            results.setText("Wins: " + wins + "  |  Losses: " + losses);
        }
    }

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        checkNumber();
    }//GEN-LAST:event_btnCheckActionPerformed

    private void numberGuessKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numberGuessKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            checkNumber();
        }
    }//GEN-LAST:event_numberGuessKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton generate;
    private java.awt.List guessList;
    private javax.swing.JTextField numberGuess;
    private javax.swing.JLabel remain;
    private javax.swing.JLabel resultText;
    private javax.swing.JLabel results;
    private javax.swing.JLabel task;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
