/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day15;

/**
 *
 * @author user
 */
public class Lists extends javax.swing.JPanel {

    /**
     * Creates new form Lists
     */
    public Lists() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        btn = new javax.swing.JButton();
        list1 = new java.awt.List();
        delete = new javax.swing.JButton();
        textField = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        average = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        btn.setText("Pievienot skaitli");
        btn.setActionCommand("");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        delete.setText("Dzēst pēdējo vērtību");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        average.setText("Aprēķināt vidējo");
        average.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                averageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(average)
                    .addComponent(delete)
                    .addComponent(btn)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(list1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(textField))
                        .addGap(21, 21, 21)
                        .addComponent(label)))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(average)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        String text = textField.getText();
//        if (!text.isEmpty()){
//            list1.add(text);
//            textField.setText("");
//        }     
        try {
            int number = Integer.valueOf(text);
            if (!text.isEmpty()) {
                list1.add(text);
                textField.setText("");
                label.setText("Ievade ok");
            }
        } catch (Exception ex) {
            label.setText("Jāievada skaitlis!");
        }

        //nospiežot pogu pievieno vērtību tikai tad, ja tur ir skaitlis
        //jauna poga, kas paņemt visus skaitļus un rēķina vidējo
        //labels, kas parāda atbildi
    }//GEN-LAST:event_btnActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        try {
            list1.remove(list1.getItemCount() - 1);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void averageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_averageActionPerformed
        double sum = 0;        
        for (int i = 0; i < list1.getItemCount(); i++) {
            int num = Integer.valueOf(list1.getItem(i));
            sum = sum + num;
        }
        double average = sum / list1.getItemCount();
        label.setText(String.valueOf(average));
        
        if (list1.getItemCount() == 0) {
            label.setText("Saraksts ir tukšs!");
        }
    }//GEN-LAST:event_averageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton average;
    private javax.swing.JButton btn;
    private javax.swing.JButton delete;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel label;
    private java.awt.List list1;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables
}
