/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Memory;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.ButtonModel;
import java.util.Collections;
import javafx.scene.control.ToggleButton;
import javax.swing.AbstractButton;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import javax.swing.Timer;
//import java.util.Timer;

/**
 *
 * @author Baiba
 */
public class Game extends javax.swing.JPanel implements ActionListener {

    /**
     * Creates new form panel2
     */
    int n = 4;
    ArrayList<JButton> buttons = new ArrayList<>(n * 2);
    ArrayList<ImageIcon> iconList = new ArrayList<>();
    JButton selected1 = null;
    JButton selected2 = null;
    boolean isMatch = false;
    //boolean hard = false;
    String time = "0 : 0";
    int moves = 0;
    int movesMed = 12;
    int movesLarge = 35;
    int count = 0;
    String iconsChosen = "";
    String diffChosen = "";
    String sizeChosen = "";
    ImageIcon icon;

    public Game() {
        initComponents();
        AddListen();
        Timer timer;
        newGame.addActionListener(actionListener);
        timerPause.addActionListener(actionListenerT);
        timerPause.setSelected(false);
        labelEnd.setText("Choose your game!");
    }

//!!!!!!!!!!!!!TODO Pārveidot taimera actiolistener
    Timer timer = new Timer(1000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            count++;
            int min = 0;
            //TODO var mēģināt saīsināt
            if (count >= 60) {
                min = count / 60;
            }
            if (count < 60) {
                min = 0;
                time = String.valueOf(min) + " : " + String.valueOf(count);
            } else {
                time = String.valueOf(min) + " : " + String.valueOf(count % (min * 60));
            }
            if (count < 3600) {
                labelTime.setText("Time: " + time);
            } else {
                ((Timer) (e.getSource())).stop();
            }
        }
    });

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        field = new javax.swing.JPanel();
        labelTime = new javax.swing.JLabel();
        timerPause = new javax.swing.JToggleButton();
        movesRem = new javax.swing.JLabel();
        labelEnd = new javax.swing.JLabel();
        panelGameChose = new javax.swing.JPanel();
        labelDifficulty = new javax.swing.JLabel();
        labelSize = new javax.swing.JLabel();
        labelImages = new javax.swing.JLabel();
        imPhotos = new javax.swing.JToggleButton();
        imClipart = new javax.swing.JToggleButton();
        imIcons = new javax.swing.JToggleButton();
        newGame = new javax.swing.JButton();
        diffNormal = new javax.swing.JToggleButton();
        diffHard = new javax.swing.JToggleButton();
        sizeMedium = new javax.swing.JToggleButton();
        sizeLarge = new javax.swing.JToggleButton();
        panelResults = new javax.swing.JPanel();

        field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        field.setMaximumSize(new java.awt.Dimension(510, 510));
        field.setPreferredSize(new java.awt.Dimension(501, 501));

        javax.swing.GroupLayout fieldLayout = new javax.swing.GroupLayout(field);
        field.setLayout(fieldLayout);
        fieldLayout.setHorizontalGroup(
            fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        fieldLayout.setVerticalGroup(
            fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        labelTime.setText("Time: ");

        timerPause.setSelected(true);
        timerPause.setText("pause");
        timerPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timerPauseActionPerformed(evt);
            }
        });

        movesRem.setText("Moves remaining: ");

        labelEnd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelEnd.setForeground(new java.awt.Color(153, 0, 0));
        labelEnd.setText("Game on!");

        labelDifficulty.setText("Difficulty:");

        labelSize.setText("Size:");

        labelImages.setText("Images:");

        imPhotos.setText("Photos");

        imClipart.setText("ClipArt");

        imIcons.setText("Icons");

        newGame.setText("New game");
        newGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameActionPerformed(evt);
            }
        });

        diffNormal.setText("Normal");

        diffHard.setText("Hard");

        sizeMedium.setText("Medium");

        sizeLarge.setText("Large");

        javax.swing.GroupLayout panelGameChoseLayout = new javax.swing.GroupLayout(panelGameChose);
        panelGameChose.setLayout(panelGameChoseLayout);
        panelGameChoseLayout.setHorizontalGroup(
            panelGameChoseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGameChoseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelGameChoseLayout.createSequentialGroup()
                    .addComponent(diffNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(diffHard, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(labelDifficulty)
                .addComponent(labelImages)
                .addGroup(panelGameChoseLayout.createSequentialGroup()
                    .addComponent(imPhotos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(imClipart, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(imIcons, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelGameChoseLayout.createSequentialGroup()
                    .addGroup(panelGameChoseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sizeMedium, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelSize))
                    .addGap(10, 10, 10)
                    .addComponent(sizeLarge, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        panelGameChoseLayout.setVerticalGroup(
            panelGameChoseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGameChoseLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(panelGameChoseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGameChoseLayout.createSequentialGroup()
                        .addComponent(labelSize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sizeMedium))
                    .addGroup(panelGameChoseLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(sizeLarge)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelDifficulty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGameChoseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(diffNormal)
                    .addComponent(diffHard))
                .addGap(11, 11, 11)
                .addComponent(labelImages)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGameChoseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imPhotos)
                    .addComponent(imClipart)
                    .addComponent(imIcons))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newGame, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelResultsLayout = new javax.swing.GroupLayout(panelResults);
        panelResults.setLayout(panelResultsLayout);
        panelResultsLayout.setHorizontalGroup(
            panelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelResultsLayout.setVerticalGroup(
            panelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(field, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEnd)
                            .addComponent(movesRem)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelTime)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(timerPause))
                                .addComponent(panelGameChose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelGameChose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTime, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(timerPause, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(movesRem)
                        .addGap(18, 18, 18)
                        .addComponent(labelEnd))
                    .addComponent(field, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameActionPerformed
        //clears old field
        field.removeAll();
        buttons.removeAll(buttons);
        iconList.removeAll(iconList);

        //creates new field
        count = 0;
        labelEnd.setText("Game on!");
        moves = (sizeChosen.equals("medium")) ? movesMed : movesLarge;
        if (diffChosen.isEmpty() || sizeChosen.isEmpty() || iconsChosen.isEmpty()) {
            System.out.println("empty");
            labelEnd.setText("Choose all game options!");
        } else {
        try {
            GridLayout();
        } catch (Exception e) {
            
        }
        }
    }//GEN-LAST:event_newGameActionPerformed

    private void timerPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timerPauseActionPerformed
        timer.stop();
    }//GEN-LAST:event_timerPauseActionPerformed
    private void AddListen() {
        imIcons.addActionListener(actionListenerT);
        imClipart.addActionListener(actionListenerT);
        imPhotos.addActionListener(actionListenerT);
        diffHard.addActionListener(actionListenerT);
        diffNormal.addActionListener(actionListenerT);
        sizeLarge.addActionListener(actionListenerT);
        sizeMedium.addActionListener(actionListenerT);
    }

    private void GridLayout() {
         
            if (diffChosen.equals("hard")) {
                movesRem.setText("Moves remaining: " + moves);
            } else {
                movesRem.setText("Moves remaining: unlimited");
            }
            labelTime.setText("Time: " + time);

//creates field and addds buttons from arraylist   
            field.setLayout(new GridLayout(n, n));
            for (int i = 0; i < n * n; i++) {
                buttons.add(new JButton());
                buttons.get(i).setName("b" + i);
                //System.out.println("add listener & button " + i);
                field.add(buttons.get(i));
                buttons.get(i).addActionListener(actionListener);
                buttons.get(i).setBackground(Color.WHITE);
            }

//creates & shuffles icons
            for (int i = 0; i < n * n / 2; i++) {
                //icon = new ImageIcon();
                switch (iconsChosen) {
                    case "photos":
                        icon = new ImageIcon("src\\images\\photos\\icon" + i + ".jpg");
                        icon = new ImageIcon("src\\images\\photos\\icon" + i + ".jpg");
                        break;
                    case "clipart":
                        icon = new ImageIcon("src\\images\\clipart\\icon" + i + ".jpg");
                        icon = new ImageIcon("src\\images\\clipart\\icon" + i + ".jpg");
                        break;
                    case "icons":
                        icon = new ImageIcon("src\\images\\icons\\icon" + i + ".jpg");
                        icon = new ImageIcon("src\\images\\icons\\icon" + i + ".jpg");
                        break;
                }
                Image resized = icon.getImage();
                if (sizeChosen.equals("medium")) {
                    resized = icon.getImage().getScaledInstance(122, 122, Image.SCALE_SMOOTH);
                }
                if (sizeChosen.equals("large")) {
                    resized = icon.getImage().getScaledInstance(81, 81, Image.SCALE_SMOOTH);
                }
                icon = new ImageIcon(resized);
                iconList.add(icon);
                iconList.add(icon);
            }
            Collections.shuffle(iconList);
        
    }

    ActionListener actionListenerT = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent evttoggle) {
            JToggleButton buttonT = (JToggleButton) evttoggle.getSource();
            //boolean selected = button.getModel().isSelected();
            String action = evttoggle.getActionCommand();

            switch (action) {
                case "Hard":
                    diffNormal.setSelected(false);
                    diffChosen = "hard";
                    System.out.println("hard");
                    break;
                case "Normal":
                    System.out.println("normal");
                    diffChosen = "normal";
                    diffHard.setSelected(false);
                    break;
                case "Medium":
                    sizeLarge.setSelected(false);
                    System.out.println("medium");
                    sizeChosen = "medium";
                    moves = movesMed;
                    n = 4;
                    break;
                case "Large":
                    sizeMedium.setSelected(false);
                    System.out.println("large");
                    sizeChosen = "large";
                    moves = movesLarge;
                    n = 6;
                    break;
                case "Photos":
                    iconsChosen = "photos";
                    imIcons.setSelected(false);
                    imClipart.setSelected(false);
                    System.out.println("photos");
                    break;
                case "Icons":
                    iconsChosen = "icons";
                    imClipart.setSelected(false);
                    imPhotos.setSelected(false);
                    System.out.println("icons");
                    break;
                case "ClipArt":
                    iconsChosen = "clipart";
                    imIcons.setSelected(false);
                    imPhotos.setSelected(false);
                    System.out.println("cliparttttt");
                    break;
            }
        }
    };

    ActionListener actionListener = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent evt) {
            try {

                if (diffChosen.equals("hard")) {
                    movesRem.setText("Moves remaining: " + moves);
                } else {
                    movesRem.setText("Moves remaining: unlimited");
                }
                timerPause.setSelected(false);
                clearIcons();
                JButton button = (JButton) evt.getSource();

                for (JButton btn : buttons) {
                    if (button == btn) {
                        System.out.println("icon name:  " + button.getName());
                        int name2 = Integer.valueOf((button.getName()).replace("b", ""));
                        button.setIcon(iconList.get(name2));
                        System.out.println("icon n:  " + button.getIcon());
                        if (selected1 == null) {
                            selected1 = button;
                            selected1.removeActionListener(this);
                        } else {
                            selected2 = button;
                            selected2.removeActionListener(this);
                        }
                        checkIcons();
                        break;
                    }
                }
                timer.setInitialDelay(1000);
                timer.start();

            } catch (Exception ex) {

            }
        }
    };

    private void clearIcons() {
        if (selected1 != null && selected2 != null) {
            selected1.addActionListener(actionListener);
            selected2.addActionListener(actionListener);
            if (!isMatch) {//sakrīt
                selected1.setIcon(null);
                selected2.setIcon(null);

            }
            selected1 = null;
            selected2 = null;
            isMatch = false;
        }
    }

    private void checkIcons() {
//checks pairs
        if (selected1 != null && selected2 != null) {
            if (selected1.getIcon() == selected2.getIcon()) {
                System.out.println("match!");
                isMatch = true;
                selected1.setEnabled(false);
                selected2.setEnabled(false);
            }
            if (selected1.getIcon() != selected2.getIcon()) {
                System.out.println("no match!");
                isMatch = false;
            }
            if (diffChosen.equals("hard")) {
                moves--;
            }
            System.out.println("Sel1: " + selected1.getName() + "  sel2: " + selected2.getName());
        }
//if moves == 0
        if (diffChosen.equals("hard")) {
            if (moves == -1) {
                labelEnd.setText("Game over!");
                timer.stop();
                for (JButton btn : buttons) {
                    btn.removeActionListener(actionListener);
                }
            }
        }
        if (diffChosen.equals("normal")) {
            System.out.println("normal going on");
        }
//TODO !!!!!!!!!!!!!Nestrādā korekti ??
//checks if every icons is revealed
        for (int i = 0; i < buttons.size(); i++) {
            if (buttons.get(i).getIcon() == null) {
                break;
            } else if (i == buttons.size() - 1) {
                System.out.println("pilns");
                labelEnd.setText("Completed!");
                timer.stop();
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton diffHard;
    private javax.swing.JToggleButton diffNormal;
    private javax.swing.JPanel field;
    private javax.swing.JToggleButton imClipart;
    private javax.swing.JToggleButton imIcons;
    private javax.swing.JToggleButton imPhotos;
    private javax.swing.JLabel labelDifficulty;
    private javax.swing.JLabel labelEnd;
    private javax.swing.JLabel labelImages;
    private javax.swing.JLabel labelSize;
    private javax.swing.JLabel labelTime;
    private javax.swing.JLabel movesRem;
    private javax.swing.JButton newGame;
    private javax.swing.JPanel panelGameChose;
    private javax.swing.JPanel panelResults;
    private javax.swing.JToggleButton sizeLarge;
    private javax.swing.JToggleButton sizeMedium;
    private javax.swing.JToggleButton timerPause;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
