/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timer;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Baiba
 */
public class Panel extends javax.swing.JPanel implements ActionListener {

    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
        labelTime.setText(String.valueOf(count));
    }
    int count = 10;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTime = new javax.swing.JLabel();
        timeStart = new javax.swing.JButton();
        timeStop = new javax.swing.JButton();
        timeNew = new javax.swing.JButton();

        labelTime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTime.setText("TIME");

        timeStart.setText("Start");
        timeStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeStartActionPerformed(evt);
            }
        });

        timeStop.setText("Stop");
        timeStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeStopActionPerformed(evt);
            }
        });

        timeNew.setText("New");
        timeNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(timeStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeStop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(timeNew)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(labelTime)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeStart)
                    .addComponent(timeStop)
                    .addComponent(timeNew))
                .addContainerGap(119, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void timeStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeStartActionPerformed
        timer.setInitialDelay(0);
        timer.start();
    }//GEN-LAST:event_timeStartActionPerformed

    private void timeStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeStopActionPerformed
        timer.stop();
    }//GEN-LAST:event_timeStopActionPerformed

    private void timeNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeNewActionPerformed
        count = 10;
        timer.stop();
        labelTime.setText(String.valueOf(count));
    }//GEN-LAST:event_timeNewActionPerformed

    Timer timer = new Timer(1000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent evt) {
            labelTime.setText(String.valueOf(count));
            if (count > 0) {
                count--;
            } else {
                labelTime.setText("Laiks beidzies!");
            }
        }
    });
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelTime;
    private javax.swing.JButton timeNew;
    private javax.swing.JButton timeStart;
    private javax.swing.JButton timeStop;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent evt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
