/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalworktry;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Baiba
 */
public class Game extends javax.swing.JPanel implements ActionListener {

    ArrayList<JButton> buttons = new ArrayList<>();
    ArrayList<ImageIcon> iconList = new ArrayList<>();

    public Game() {
        initComponents();

        label.setText(String.valueOf(moves));
        label2.setText("Pirmais logs");

        
        Collections.addAll(buttons, b1, b2, b3, b4, b5, b6, b7, b8, b9);

        ImageIcon icon2 = new ImageIcon("src\\images\\icon2.jpg");
        ImageIcon icon3 = new ImageIcon("src\\images\\icon3.jpg");
        ImageIcon icon4 = new ImageIcon("src\\images\\icon4.jpg");
        Collections.addAll(iconList, icon2, icon3, icon3, icon4, icon4);
        Collections.addAll(iconList, icon2, icon3, icon3, icon4, icon4);
        Collections.shuffle(iconList);
        drawField();
    }

    boolean visible = true;
    boolean nextMove = false;
    boolean noMatch = false;
    int moves = 2;
    JButton selected1 = null;
    JButton selected2 = null;
    int index;
    ImageIcon defIcon = new ImageIcon("src\\images\\icon.jpg");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();

        b1.setName("b1"); // NOI18N

        b2.setName("b2"); // NOI18N
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setName("b3"); // NOI18N
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.setName("b4"); // NOI18N

        b5.setName("b5"); // NOI18N
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.setName("b6"); // NOI18N
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b7.setEnabled(false);

        b8.setName("b8"); // NOI18N
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b9.setName("b9"); // NOI18N
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        label.setText("jLabel1");

        label2.setText("jLabel1");

        label3.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(label)
                        .addGap(69, 69, 69)
                        .addComponent(label2)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(label3))
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(b1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label)
                    .addComponent(label2)
                    .addComponent(label3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void drawField() {
        for (int i = 1; i < 10; i++) {
            buttons.add(new JButton("b" + i));
        }
        //sets names for all buttons and adds actionListeners
        for (int i = 0; i < buttons.size(); i++) {
            buttons.get(i).setName("b" + i);
            buttons.get(i).addActionListener(this);
        }
    }

    @Override
    public void actionPerformed(ActionEvent evt) {
        JButton button = (JButton) evt.getSource();
        System.out.println(button.getName()); // check
        for (int i = 0; i < buttons.size(); i++) {
            if (button == buttons.get(i)) {
                index = i;
                System.out.println("image index: " + i);
                button.setIcon(iconList.get(i));
            }
        }

        System.out.println("icon name:  " + button.getIcon()); //check
    }

    private void clearIcons() {
        if (!noMatch) {
            label2.setText("nesakrīt222");
            selected1.setIcon(null);
            selected2.setIcon(null);
        }
        if (noMatch) {//sakrīt
            selected1.setIcon(null);
            selected2.setIcon(null);
            selected1 = null;
            selected2 = null;
        }

    }

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
//        b9.addActionListener(this);
//        index = 8;
//        if (noMatch) {
//            clearIcons();
//        }
//        if (b9 != selected1 || b9 != selected2) {
//            if (selected1 == null) {
//                selected1 = b9;
//            }
//            if (selected1 != null) {
//                selected2 = b9;
//            }
//            b9.setIcon(iconList.get(8));
//            moves--;
//            countMoves();
//            matchIcons();
//
//        }
//        for (int i = buttons.size(); i < buttons.size(); i++) {
//            if (b9 == buttons.get(i))
//            {
//                b9.setIcon(iconList.get(i));
//                break;        
//            } 
//        }

    }//GEN-LAST:event_b9ActionPerformed


    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
//        b6.addActionListener(this);
//        index = 5;
//        if (noMatch) {
//            clearIcons();
//        }
//        if (b6 != selected1 || b6 != selected2) {
//            if (selected1 == null) {
//                selected1 = b6;
//            }
//            if (selected1 != null) {
//                selected2 = b6;
//            }
//            b6.setIcon(iconList.get(5));
//            moves--;
//            countMoves();
//            matchIcons();
//        }

    }//GEN-LAST:event_b6ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
//        b3.addActionListener(this);
//        index = 2;
//        if (noMatch) {
//            clearIcons();
//        }
//        if (b3 != selected1 || b3 != selected2) {
//            if (selected1 == null) {
//                selected1 = b3;
//            }
//            if (selected1 != null) {
//                selected2 = b3;
//            }
//            b3.setIcon(iconList.get(2));
//            moves--;
//            countMoves();
//            matchIcons();
//        }

    }//GEN-LAST:event_b3ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
//        b2.addActionListener(this);
//        index = 1;
//        if (noMatch) {
//            clearIcons();
//        }
//        if (b2 != selected1 || b2 != selected2) {
//            if (selected1 == null) {
//                selected1 = b2;
//            }
//            if (selected1 != null) {
//                selected2 = b2;
//            }
//            b2.setIcon(iconList.get(1));
//            moves--;
//
//            matchIcons();
//            countMoves();
//
//        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
//        b5.addActionListener(this);
//        index = 4;
    }//GEN-LAST:event_b5ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
//        b8.addActionListener(this);
//        index = 7;
    }//GEN-LAST:event_b8ActionPerformed
    private void matchIcons() {
//        if (selected1 == null || selected2 == null){
//            nextMove = false;
//        }
        if (selected1 != null && selected2 != null) {
            if (selected1.getIcon() == selected2.getIcon()) {
                label2.setText("sakrīt!");
                nextMove = false;
                noMatch = false;
            }
            if (selected1.getIcon() != selected2.getIcon()) {
                label2.setText("nesakrīt");
//                selected1.setIcon(defIcon);
//                selected2.setIcon(defIcon);
                nextMove = false;
                noMatch = true;

            }

        } else {
            nextMove = false;
        }

//        label2.setText("nesakrīt");
//        selected1.setIcon(null);
//        selected2.setIcon(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    // End of variables declaration//GEN-END:variables


}
